server:
    servlet:
        # Define o caminho de contexto que a aplicação usuará.
        contextPath: /treinamento
    messages:
        encoding: UTF-8
    tomcat:
        uri-encoding: UTF-8
    # Define a porta em que a aplicação irá executar
    port: ${PORT:9595}
    
spring:
    #Responsável pela configuração de security do spring
    security:
       # Configura um usuário padrão com usuario e senha admin e role ADMIN
        user:
            name: admin
            password: admin
            roles: ADMIN
    # Configura como o sistema trabalhará as interações com o banco de dados
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: ${SHOW_SQL:true}
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    # Configura o acesso ao banco de dados
    datasource:
        # Variáveis criadas por usuário
        host: ${DATABASE_HOST:localhost}
        port: ${DATABASE_PORT:3306}
        database: ${DATABASE:treinamento}
        # Configuração da url de acesso ao banco
        url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.datasource.database}?useUnicode=true&autoReconnect=true
        # Usuário e senha do banco
        username: ${DATABASE_USER:treinamento}
        password: ${DATABASE_PASSWORD:treinamento}
        driverClassName: com.mysql.cj.jdbc.Driver
        # Configurações do spring para acesso ao banco.
        hikari:
            auto-commit: true
            connection-test-query: select 1 from dual;
            connection-init-sql: SET time_zone='-3:00';
            minimum-idle: 3
            maximum-pool-size: 100

#Configuração de log
logging:
    file:
      name: /var/log/treinamento/treinamento.log
      max-history: 2
      max-size: 10MB
    level:
        root: ERROR
        org.springframework: ERROR   
        com.minsait.treinamento.AppStarter: INFO
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Definições relativas ao swagger
springfox:
    documentation:
        # Permite ativar/desativar o swagger
        enabled: true

# Variáveis definidas pelo Dev para funções da aplicação
treinamento:
    # Define de onde serão tirados os textos das mensagens do app.
    custom-message:
        bundle:
            name: messages-prod
            extension: properties
            charset: java.nio.charset.StandardCharsets.ISO_8859_1
    security-ativo: true