server:
    servlet:
        contextPath: /treinamento
    messages:
        encoding: UTF-8
    tomcat:
        uri-encoding: UTF-8
    # Define a porta em que a aplicação irá executar
    port: ${PORT:8080}
    
spring:
    # Configura como o sistema trabalhará as interações com o banco de dados
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: ${SHOW_SQL:true}
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    datasource:
        # Configuração da URL de acesso ao banco
        url: jdbc:mysql://${app.datasource.host}:${app.datasource.port}/${app.datasource.database}?useUnicode=true&autoReconnect=true
        # Usuário e senha do banco
        username: ${DATABASE_USER:treinamentoindra}
        password: ${DATABASE_PASSWORD:treinamentoindra}
        driverClassName: com.mysql.cj.jdbc.Driver
        hikari:
            auto-commit: true
            connection-test-query: select 1 from dual;
            connection-init-sql: SET time_zone='-3:00';
            minimum-idle: 3
            maximum-pool-size: 100

logging:
    file:
        name: /var/log/treinamento/treinamento.log
        max-history: 2
        max-size: 10MB
    level:
        root: ERROR
        org.springframework: ERROR   
        com.minsait.treinamento.AppStarter: INFO
    pattern:
        console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'
        file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

app:
    custom-message:
        bundle:
            extension: properties
            charset: java.nio.charset.StandardCharsets.ISO_8859_1        
    # Configura o acesso ao banco de dados
    datasource:
        host: ${DATABASE_HOST:31.220.109.68}
        port: ${DATABASE_PORT:3306}
        database: ${DATABASE:treinamentoindra}
