spring:
    cors:
        allowed-origins: http://localhost:4200
        allowed-methods: GET, POST, PUT, DELETE
    profiles:
        # Define qual o profile que será usado durante a execução
        active: ${ACTIVE_PROFILE:default}

    autoconfigure:
        exclude:
            # Isso impede que o springboot configure o security por conta própria
            - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Variáveis definidas pelo Dev para funções da aplicação
app:
    # Define de onde serão tirados os textos das mensagens do app.
    custom-message:
        bundle:
            name: messages-${spring.profiles.active}
